<?xml version="1.0"?>
<robot name="segway" xmlns:xacro="http://ros.org/wiki/xacro">


  <!-- SIZE BODY -->
  <xacro:property name="width_body" value="0.295" />
  <xacro:property name="height_body" value="0.35" />
  <xacro:property name="depth_body" value="0.05" />


  <!-- SIZE WHEEL -->
  <xacro:property name="diam_wheel" value="0.125" />
  <xacro:property name="len_wheel" value="0.03" />

  <!-- SIZE CAMERA -->
  <xacro:property name="cameraSize" value="0.05"/>
  <xacro:property name="cameraMass" value="0.1"/>


  <!-- Import all Gazebo-customization elements -->
  <xacro:include filename="$(find quimesis_segway_description)/urdf/segway.gazebo" />


  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>


  <!-- INERTIAL -->
  <xacro:macro name="cylinder_inertial_with_origin" params="radius length mass *origin">
     <inertial>
       <mass value="${mass}" />
       <xacro:insert_block name="origin" />
       <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
         iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
         izz="${0.5 * mass * radius * radius}" />
     </inertial>
  </xacro:macro>

  <xacro:macro name="inertial_with_origin" params="radius length mass izz *origin">
     <inertial>
       <mass value="${mass}" />
       <xacro:insert_block name="origin" />
       <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
         iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
         izz="${izz}" />
     </inertial>
  </xacro:macro>


  <!-- ROBOT -->

<link name="footprint" />

  <joint name="base_joint" type="fixed">
  <origin xyz="0 1 0" rpy="0 0 0"/>
    <parent link="footprint"/>
    <child link="base_link"/>
  </joint>

  <link name="base_link">
    <gazebo>
      <static>true</static>
    </gazebo>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <!-- <mesh filename="package://quimesis_segway_description/meshes/Segway_without_wheels.STL" scale="1.0"/> -->
          <box size="${depth_body} ${width_body} ${height_body} "/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${depth_body} ${width_body} ${height_body} "/>
      </geometry>
    </collision>

    <inertial>
      <mass value="3.4" />
      <origin xyz="0 0 -0.08" rpy="0 0 0" />
      <inertia ixx="0.05" ixy="0.0" ixz="0.0"
        iyy="0.49" iyz="0.0"
        izz="0.055" />
    </inertial>
  </link>



  <!-- Wheel MACRO -->
  <xacro:macro name="wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${diam_wheel/2}" length="${len_wheel}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${diam_wheel/2}" length="${len_wheel}"/>
        </geometry>
      </collision>
      <xacro:inertial_with_origin radius="${diam_wheel/2}" length="${len_wheel}" mass="0.188" izz="0.0006" >
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      </xacro:inertial_with_origin >
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 1 0" />
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="0 ${reflect*(width_body/2 + len_wheel/2)} -0.15" rpy="0 0 0"/>
    </joint>

    <gazebo reference="${prefix}_wheel">
      <mu1 value="1e+16"/>
      <mu2 value="1e+16"/>
    </gazebo>
  </xacro:macro>

  <!-- WHEELs -->
  <xacro:wheel prefix="left" reflect="-1" />
  <xacro:wheel prefix="right" reflect="1" />

 <!-- CAMERA -->

<joint name="joint1" type="fixed">
    <origin xyz="0 0 ${height_body/2+0.025}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="camera"/>
  </joint>

<link name="camera">
    <collision>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
        ixx="0.01" ixy="0.0" ixz="0.0"
        iyy="0.01" iyz="0.0"
        izz="0.01"/>
    </inertial>
  </link>

-->


  </robot>
